enum KeyMap {
  leftMouseButton,
  rightMouseButton,
  controlBreakProcessing,
  middleMouseButton,
  x1MouseButton,
  x2MouseButton,
  backspace,
  tab,
  clear,
  enter,
  shift,
  control,
  alt,
  pause,
  capsLock,
  imeHangulMode, // no idea what this is (windows)
  imeOn, // no idea what this is (windows)
  imeJunjaMode, // no idea what this is (windows)
  imeFinalMode, // no idea what this is (windows)
  imeHanjaMode, // no idea what this is (windows)
  imeKanjiMode, // no idea what this is (windows)
  imeOff, // no idea what this is (windows)
  escape,
  imeConvert, // no idea what this is (windows)
  imeNonConvert, // no idea what this is (windows)
  imeAccept, // no idea what this is (windows)
  imeModeChangeRequest, // no idea what this is (windows)
  space,
  pageUp,
  pageDown,
  end,
  home,
  arrowLeft,
  arrowUp,
  arrowRight,
  arrowDown,
  select,
  print,
  execute,
  printScreen,
  insert,
  delete,
  help,
  digit0,
  digit1,
  digit2,
  digit3,
  digit4,
  digit5,
  digit6,
  digit7,
  digit8,
  digit9,
  keyA,
  keyB,
  keyC,
  keyD,
  keyE,
  keyF,
  keyG,
  keyH,
  keyI,
  keyJ,
  keyK,
  keyL,
  keyM,
  keyN,
  keyO,
  keyP,
  keyQ,
  keyR,
  keyS,
  keyT,
  keyU,
  keyV,
  keyW,
  keyX,
  keyY,
  keyZ,
  metaLeft,
  metaRight,
  contextMenu,
  sleep,
  numpad0,
  numpad1,
  numpad2,
  numpad3,
  numpad4,
  numpad5,
  numpad6,
  numpad7,
  numpad8,
  numpad9,
  numpadMultiply,
  numpadAdd,
  numpadComma,
  numpadSubtract,
  numpadDecimal,
  numpadDivide,
  f1,
  f2,
  f3,
  f4,
  f5,
  f6,
  f7,
  f8,
  f9,
  f10,
  f11,
  f12,
  f13,
  f14,
  f15,
  f16,
  f17,
  f18,
  f19,
  f20,
  f21,
  f22,
  f23,
  f24,
  numLock,
  scrollLock,
  shiftLeft,
  shiftRight,
  controlLeft,
  controlRight,
  altLeft,
  altRight,
  browserBack,
  browserForward,
  browserRefresh,
  browserStop,
  browserSearch,
  browserFavorites,
  browserHome,
  audioVolumeMute,
  audioVolumeDown,
  audioVolumeUp,
  mediaTrackNext,
  mediaTrackPrevious,
  mediaStop,
  mediaPlayPause,
  launchMail,
  selectMediaKey,
  launchApplication1,
  launchApplication2,
  semicolon,
  equal,
  comma,
  minus,
  period,
  slash,
  backquote,
  bracketLeft,
  backslash,
  bracketRight,
  quote,
  vkOem8, // no idea what this is (windows)
  imeProcessKey, // no idea what this is (windows)
  vkPacket, // no idea what this is (windows)
  vkAttn, // no idea what this is (windows)
  vkCrSel, // no idea what this is (windows)
  vkExSel, // no idea what this is (windows)
  vkErEOF, // no idea what this is (windows)
  vkPlay, // no idea what this is (windows)
  vkZoom, // no idea what this is (windows)
  vkNoName, // no idea what this is (windows)
  vkPA1, // no idea what this is (windows)
  vkOemClear // no idea what this is (windows)
}
